spring:
  application:
    name: theater_proj
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate.hibernate.default_batch_fetch_size: 100
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
jwt:
  secret: "theaterprojectsecretkey1234theaterprojectsecretkey1234theaterprojectsecretkey1234"
  access-token-expiration-ms: 360000
  refresh-token-expiration-ms: 1209600000
server:
  port: 8088
